.common: &common
    hostname: ~
    port: 22
    user: root
    password: ~
    longview-mysql-pass: ~
    forward_agent: true
    identity_file: ~
    stage: production
    app_path: ./deploy/apps/web
    deploy_path: /var/www/web
    server_name: myserver.com
    local_parameters: ./app/config/parameters.yml
    repository: ~
    branch: master
    cloudflare:
        email: ~
        api_key: ~
        domain: ~
    defines: ~
    tasks:
        before: ~
        after: ~
        task: ~

.substitutions: &substitutions
    EDIT_ME_SF_CMD: '{{sf}}'
    EDIT_ME_DEPLOY_PATH: '{{deploy_path}}'
    EDIT_ME_PHP_FASTCGI: '{{php_fastcgi}}'
    EDIT_ME_SERVER_NAME: '{{server_name}}'
    EDIT_ME_SERVER_TIMEZONE: '{{timezone}}'

.environments: &environments
        php_version: 7.2
        php_fastcgi: /run/php/php7.2-fpm.sock
        cachetool: true
        http_strict_server_name: false
        timezone: Asia/Bangkok
        writable_mode: chmod
        writable_chmod_mode: '0777'
        writable_use_sudo: false
        symfony_env: prod
        dump_assets: false
        sylius_theme_used: false
        shared_dirs:
            - var/logs
            - var/sessions
            - web/media
        shared_files:
            - app/config/parameters.yml
        writable_dirs:
            - var/cache
            - var/logs
            - var/sessions
            - web/media
        assets:
            - web/assets
            - web/bundles
        copy_dirs:
            - vendor
            - web/assets
            - web/bundles
        copy_files:
            - var/bootstrap.php.cache
        copy_local_dirs:
            - web/assets
            - web/bundles
        copy_local_files: ~
